### ISSUE TITLE
mbed-tools new . doesn't work because set(APP_TARGET ) in CMakeLists.txt

### ISSUE THREAD

**Issue by adepier** [ARMmbed/Handbook#1413] opened 2021-02-10 19:46 UTC
# Docs issue template
when it says : "If you have already created a project folder, you can use ."  
## Page link
https://os.mbed.com/docs/mbed-os/v6.6/build-tools/use.html
## Expected to find...
you should add a precision "then complete in CMakeLists.txt, the line set(APP_TARGET "project folder")

**Comment by 0xc0170** [comment] 2021-02-10 20:15
APP_TARGET should not be required in the app if you are using new mbed-tools and latest Mbed OS master. There is a bug we are fixing (it should be fixed tomorrow on master).

Thanks for reporting

**Comment by 0xc0170** [comment] 2021-02-10 20:15
As this is not a bug in docs, I'll close this

This is the fix : https://github.com/ARMmbed/mbed-os/pull/14265

**Closed as completed by 0xc0170** 2021-02-10 20:15 UTC
